//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewRes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SafiMed.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SafiMed is an enterprise with core competencies in marketing and distribution of pharmaceuticals and medicines (medical devices, consumables, medical equipment, remedies, biochemical products, nutritional supplements,  medicinal cosmetics)..
        /// </summary>
        public static string AboutTab1BodyText1 {
            get {
                return ResourceManager.GetString("AboutTab1BodyText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SafiMed is driven by a dedicated team of professionals with profound international expertise in applied medicine, consulting, registration, marketing and distribution..
        /// </summary>
        public static string AboutTab1BodyText2 {
            get {
                return ResourceManager.GetString("AboutTab1BodyText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professional logistic, distributors and representative network, network of partners and experts, as well as strong marketing and registration services allow SafiMed to provide supply flexibility, efficient registration and marketing..
        /// </summary>
        public static string AboutTab1BodyText3 {
            get {
                return ResourceManager.GetString("AboutTab1BodyText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oftentimes, manufacturing companies have great innovative products, but do not possess the resources to take full advantage of brand-new business opportunities. This is where SafiMed can play a key role..
        /// </summary>
        public static string AboutTab1BodyText4 {
            get {
                return ResourceManager.GetString("AboutTab1BodyText4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SafiMed was founded to provide integrated business solutions for the healthcare areas, so that manufacturers&apos; potential meet individual needs of multiple HCPs and customers..
        /// </summary>
        public static string AboutTab1BodyText5 {
            get {
                return ResourceManager.GetString("AboutTab1BodyText5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can request detailed information, get a full company &amp; services presentation, and receive our answers to your questions by.
        /// </summary>
        public static string AboutTab1BodyText6 {
            get {
                return ResourceManager.GetString("AboutTab1BodyText6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contacting us..
        /// </summary>
        public static string AboutTab1BodyText6Link {
            get {
                return ResourceManager.GetString("AboutTab1BodyText6Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WHO WE ARE.
        /// </summary>
        public static string AboutTab1BodyTitle {
            get {
                return ResourceManager.GetString("AboutTab1BodyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A bridge between the manufacturer and consumers.
        /// </summary>
        public static string AboutTab1Title {
            get {
                return ResourceManager.GetString("AboutTab1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using &quot;full-cycle support&quot; principle we ensure business development and promotion on new markets for manufacturers of pharmaceutical and medical products, starting with primary market analysis and ending with the delivery to the final consumer..
        /// </summary>
        public static string AboutTab2BodyText1 {
            get {
                return ResourceManager.GetString("AboutTab2BodyText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consulting services:.
        /// </summary>
        public static string AboutTab2BodyText2 {
            get {
                return ResourceManager.GetString("AboutTab2BodyText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market Research.
        /// </summary>
        public static string AboutTab2BodyText2Part1 {
            get {
                return ResourceManager.GetString("AboutTab2BodyText2Part1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products registration support.
        /// </summary>
        public static string AboutTab2BodyText2Part2 {
            get {
                return ResourceManager.GetString("AboutTab2BodyText2Part2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commercial services:.
        /// </summary>
        public static string AboutTab2BodyText3 {
            get {
                return ResourceManager.GetString("AboutTab2BodyText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marketing.
        /// </summary>
        public static string AboutTab2BodyText3Part1 {
            get {
                return ResourceManager.GetString("AboutTab2BodyText3Part1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distributions and Sales.
        /// </summary>
        public static string AboutTab2BodyText3Part2 {
            get {
                return ResourceManager.GetString("AboutTab2BodyText3Part2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Being deeply aware of the current challenges arising in highly developing markets in CE, we choose to prioritise reliable risk management strategies, founded on EU effective legal rules..
        /// </summary>
        public static string AboutTab2BodyText4 {
            get {
                return ResourceManager.GetString("AboutTab2BodyText4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owing to professional experience in the pharmaceutical and medical field gained by its team, our company is the ideal partner for consulting, marketing, and distribution services..
        /// </summary>
        public static string AboutTab2BodyText5 {
            get {
                return ResourceManager.GetString("AboutTab2BodyText5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can request detailed information, get a full company &amp; services presentation, and receive our answers to your questions by.
        /// </summary>
        public static string AboutTab2BodyText6 {
            get {
                return ResourceManager.GetString("AboutTab2BodyText6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contacting us..
        /// </summary>
        public static string AboutTab2BodyText6Link {
            get {
                return ResourceManager.GetString("AboutTab2BodyText6Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WHAT WE DO.
        /// </summary>
        public static string AboutTab2BodyTitle {
            get {
                return ResourceManager.GetString("AboutTab2BodyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive your sales growth from international opportunities.
        /// </summary>
        public static string AboutTab2Title {
            get {
                return ResourceManager.GetString("AboutTab2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OUR MISSION STATEMENT.
        /// </summary>
        public static string AboutTab3BodyText1 {
            get {
                return ResourceManager.GetString("AboutTab3BodyText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are committed to providing high-quality services using &quot;full-cycle&quot; principle, when we can fulfill the quality control on each step..
        /// </summary>
        public static string AboutTab3BodyText10 {
            get {
                return ResourceManager.GetString("AboutTab3BodyText10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEAMWORK.
        /// </summary>
        public static string AboutTab3BodyText11 {
            get {
                return ResourceManager.GetString("AboutTab3BodyText11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re proud of our team. Each member of our team is an expert in his own sphere and each one acknowledges the influence of the individual achievements on the common result. .
        /// </summary>
        public static string AboutTab3BodyText12 {
            get {
                return ResourceManager.GetString("AboutTab3BodyText12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CUSTOMER FOCUS.
        /// </summary>
        public static string AboutTab3BodyText13 {
            get {
                return ResourceManager.GetString("AboutTab3BodyText13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We act with commitment to ethics, honesty and compliance in building of collaborative and lasting relationships with our partners and customers..
        /// </summary>
        public static string AboutTab3BodyText14 {
            get {
                return ResourceManager.GetString("AboutTab3BodyText14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These values determine behavior standards of both the company and each employee on business market..
        /// </summary>
        public static string AboutTab3BodyText15 {
            get {
                return ResourceManager.GetString("AboutTab3BodyText15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We improve public health and also the life quality, making the best available for those who need it..
        /// </summary>
        public static string AboutTab3BodyText2 {
            get {
                return ResourceManager.GetString("AboutTab3BodyText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OUR VISION.
        /// </summary>
        public static string AboutTab3BodyText3 {
            get {
                return ResourceManager.GetString("AboutTab3BodyText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SafiMed company creates long-term confidential relations, maintaining our leadership as a reliable partner, focusing on up-to-date healthcare business tendencies and the latest market needs..
        /// </summary>
        public static string AboutTab3BodyText4 {
            get {
                return ResourceManager.GetString("AboutTab3BodyText4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OUR CORE VALUES.
        /// </summary>
        public static string AboutTab3BodyText5 {
            get {
                return ResourceManager.GetString("AboutTab3BodyText5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our values are the principles, by which we are guided help to define who we are and the kind of company we aim to be. They influence the way we work with each other – and the way we serve our partners, clients and medical society..
        /// </summary>
        public static string AboutTab3BodyText6 {
            get {
                return ResourceManager.GetString("AboutTab3BodyText6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEADERSHIP.
        /// </summary>
        public static string AboutTab3BodyText7 {
            get {
                return ResourceManager.GetString("AboutTab3BodyText7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leadership is a state of action, while developing, improving our professional level..
        /// </summary>
        public static string AboutTab3BodyText8 {
            get {
                return ResourceManager.GetString("AboutTab3BodyText8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QUALITY.
        /// </summary>
        public static string AboutTab3BodyText9 {
            get {
                return ResourceManager.GetString("AboutTab3BodyText9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OUR MISSION, VISION  AND VALUES.
        /// </summary>
        public static string AboutTab3BodyTitle {
            get {
                return ResourceManager.GetString("AboutTab3BodyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The company’s services are designed to benefit people and improve the quality of life.
        /// </summary>
        public static string AboutTab3Title {
            get {
                return ResourceManager.GetString("AboutTab3Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We serve the purpose to give the manufacturers of pharmaceuticals and medicines an opportunity to conduct innovative business operations on new markets of Eastern Europe and Central Asia..
        /// </summary>
        public static string AboutTab4BodyText1 {
            get {
                return ResourceManager.GetString("AboutTab4BodyText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We use comprehensive approach combining all the processes of marketing and distribution into entire precisely operating business system, which is managed by our company  in close coordination with manufacturer..
        /// </summary>
        public static string AboutTab4BodyText2 {
            get {
                return ResourceManager.GetString("AboutTab4BodyText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are always eager to establish relationships with manufacturers of pharmaceutical products and medical devices..
        /// </summary>
        public static string AboutTab4BodyText3 {
            get {
                return ResourceManager.GetString("AboutTab4BodyText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We provide complex follow-up support of regulatory processes of all medical and pharmaceutical products as well..
        /// </summary>
        public static string AboutTab4BodyText4 {
            get {
                return ResourceManager.GetString("AboutTab4BodyText4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our team, representative offices network, potential and experience that we have, will always help you in developing your business. We use international strategy for doing business and building partnership relations. Being aware of the peculiarities of perspective markets, which are unknown for you, we can minimize your risks when entering these markets..
        /// </summary>
        public static string AboutTab4BodyText5 {
            get {
                return ResourceManager.GetString("AboutTab4BodyText5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SafiMed company helps to develop your business using actual up-to-date business solutions, making your business manageable, favourable, flexible and open on the new territories..
        /// </summary>
        public static string AboutTab4BodyText6 {
            get {
                return ResourceManager.GetString("AboutTab4BodyText6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yours sincerely,.
        /// </summary>
        public static string AboutTab4BodyText7 {
            get {
                return ResourceManager.GetString("AboutTab4BodyText7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marina Sheveleva.
        /// </summary>
        public static string AboutTab4BodyText8 {
            get {
                return ResourceManager.GetString("AboutTab4BodyText8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Managing Director.
        /// </summary>
        public static string AboutTab4BodyText9 {
            get {
                return ResourceManager.GetString("AboutTab4BodyText9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MANAGING DIRECTOR’S MESSAGE.
        /// </summary>
        public static string AboutTab4BodyTitle {
            get {
                return ResourceManager.GetString("AboutTab4BodyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strong foundation in the years ahead.
        /// </summary>
        public static string AboutTab4Title {
            get {
                return ResourceManager.GetString("AboutTab4Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SafiMed Company Head Office is located in Riga, Latvija. .
        /// </summary>
        public static string AboutTab5BodyText1 {
            get {
                return ResourceManager.GetString("AboutTab5BodyText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company is operating in the territories of the Baltic States (Lithuania, Latvia, Estonia) and CES (Common Economic Space – Belarus, Russian Federation, Armenia, Kazakhstan, Kyrgyzstan) through its Resident Representatives and partner network..
        /// </summary>
        public static string AboutTab5BodyText2 {
            get {
                return ResourceManager.GetString("AboutTab5BodyText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latvian Centre coordinates operation of regional representatives in all countries of residence. Our company cooperates with European logistic operators, so we can guarantee  warehouse storage according to GDP Standards..
        /// </summary>
        public static string AboutTab5BodyText3 {
            get {
                return ResourceManager.GetString("AboutTab5BodyText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A company&apos;s subsidiary is most widly presented in Minsk, Republic of Belarus. Company representatives are involved in registration processes, logistics, they are also coordinating marketing and distribution..
        /// </summary>
        public static string AboutTab5BodyText4 {
            get {
                return ResourceManager.GetString("AboutTab5BodyText4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can request detailed information, get a full company &amp; services presentation, and receive our answers to your questions by.
        /// </summary>
        public static string AboutTab5BodyText5 {
            get {
                return ResourceManager.GetString("AboutTab5BodyText5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contacting us..
        /// </summary>
        public static string AboutTab5BodyText5Link {
            get {
                return ResourceManager.GetString("AboutTab5BodyText5Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OFFICE NETWORK.
        /// </summary>
        public static string AboutTab5BodyTitle {
            get {
                return ResourceManager.GetString("AboutTab5BodyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intensive development is our primary strategic objective.
        /// </summary>
        public static string AboutTab5Title {
            get {
                return ResourceManager.GetString("AboutTab5Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        public static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMMERCIAL SERVICES.
        /// </summary>
        public static string CommercialService {
            get {
                return ResourceManager.GetString("CommercialService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combination of our breadth of commercial capabilities with profound expertise across a broad range of therapeutics allows us to implement business solutions..
        /// </summary>
        public static string CommercialServiceText {
            get {
                return ResourceManager.GetString("CommercialServiceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONSULTING SERVICES.
        /// </summary>
        public static string ConsultingService {
            get {
                return ResourceManager.GetString("ConsultingService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analytical data in our hands transforms from bare statistics into your powerful decision-making tool..
        /// </summary>
        public static string ConsultingServiceText {
            get {
                return ResourceManager.GetString("ConsultingServiceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string ContactFormComp {
            get {
                return ResourceManager.GetString("ContactFormComp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can contact us using the form below. All fields are required..
        /// </summary>
        public static string ContactFormDesc {
            get {
                return ResourceManager.GetString("ContactFormDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail.
        /// </summary>
        public static string ContactFormEMail {
            get {
                return ResourceManager.GetString("ContactFormEMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string ContactFormMail {
            get {
                return ResourceManager.GetString("ContactFormMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ContactFormName {
            get {
                return ResourceManager.GetString("ContactFormName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string ContactFormPhone {
            get {
                return ResourceManager.GetString("ContactFormPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string ContactFormSend {
            get {
                return ResourceManager.GetString("ContactFormSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback form.
        /// </summary>
        public static string ContactFormTitle {
            get {
                return ResourceManager.GetString("ContactFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head Office in Latvia:.
        /// </summary>
        public static string ContactsBodyText1 {
            get {
                return ResourceManager.GetString("ContactsBodyText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «SafiMed» SIA.
        /// </summary>
        public static string ContactsBodyText2 {
            get {
                return ResourceManager.GetString("ContactsBodyText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marketing and Distribution of medical products.
        /// </summary>
        public static string ContactsBodyText3 {
            get {
                return ResourceManager.GetString("ContactsBodyText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company code: ххххххххххххх.
        /// </summary>
        public static string ContactsBodyText4 {
            get {
                return ResourceManager.GetString("ContactsBodyText4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address: Krišjāņa Valdemāra iela 18-7, Rīga, Latvia LV-1010.
        /// </summary>
        public static string ContactsBodyText5 {
            get {
                return ResourceManager.GetString("ContactsBodyText5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile (LV): +‎371 24 86 24 22.
        /// </summary>
        public static string ContactsBodyText6 {
            get {
                return ResourceManager.GetString("ContactsBodyText6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone (LV): ‎+371 24 86 24 22.
        /// </summary>
        public static string ContactsBodyText7 {
            get {
                return ResourceManager.GetString("ContactsBodyText7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e-mail:.
        /// </summary>
        public static string ContactsBodyText8 {
            get {
                return ResourceManager.GetString("ContactsBodyText8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTACTS.
        /// </summary>
        public static string ContactsBodyTitle {
            get {
                return ResourceManager.GetString("ContactsBodyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YOUR RELIABLE PARTNER IN HEALTHCARE BUSINESS DEVELOPMENT.
        /// </summary>
        public static string ContactsTitle {
            get {
                return ResourceManager.GetString("ContactsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cooperation.
        /// </summary>
        public static string Cooperation {
            get {
                return ResourceManager.GetString("Cooperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product registration support.
        /// </summary>
        public static string CooperationTab1BodyTab1 {
            get {
                return ResourceManager.GetString("CooperationTab1BodyTab1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market research and analytics.
        /// </summary>
        public static string CooperationTab1BodyTab2 {
            get {
                return ResourceManager.GetString("CooperationTab1BodyTab2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribution and sale.
        /// </summary>
        public static string CooperationTab1BodyTab3 {
            get {
                return ResourceManager.GetString("CooperationTab1BodyTab3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marketing strategy and Market Access development and implementation.
        /// </summary>
        public static string CooperationTab1BodyTab4 {
            get {
                return ResourceManager.GetString("CooperationTab1BodyTab4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SafiMed’s business model for cooperation with manufacturers is based upon exclusive presentation of products in the territory of the Baltic States (Lithuania, Latvia and Estonia) and Eurasian Economic Union (Belarus, Russian Federation, Armenia, Kazakhstan and Kyrgyzstan)..
        /// </summary>
        public static string CooperationTab1BodyText1 {
            get {
                return ResourceManager.GetString("CooperationTab1BodyText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We offer cooperation to our potential partners using &quot;full support&quot; principle starting from market investigation and finishing the sale and delivery of the product to the customer..
        /// </summary>
        public static string CooperationTab1BodyText2 {
            get {
                return ResourceManager.GetString("CooperationTab1BodyText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We act with commitment to ethics and other principles accepted in our clients&apos; and partners&apos; companies..
        /// </summary>
        public static string CooperationTab1BodyText3 {
            get {
                return ResourceManager.GetString("CooperationTab1BodyText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COOPERATION PRINCIPLES.
        /// </summary>
        public static string CooperationTab1BodyTitle {
            get {
                return ResourceManager.GetString("CooperationTab1BodyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full compliance with the values of our partners.
        /// </summary>
        public static string CooperationTab1Title {
            get {
                return ResourceManager.GetString("CooperationTab1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market Research.
        /// </summary>
        public static string CooperationTab2BodyText1 {
            get {
                return ResourceManager.GetString("CooperationTab2BodyText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using the aspects of business environment, we will perform marketing investigations of the market based on your individual requirements..
        /// </summary>
        public static string CooperationTab2BodyText2 {
            get {
                return ResourceManager.GetString("CooperationTab2BodyText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analytical data in our hands transforms from bare statistics into your powerful decision-making tool..
        /// </summary>
        public static string CooperationTab2BodyText3 {
            get {
                return ResourceManager.GetString("CooperationTab2BodyText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products registration support.
        /// </summary>
        public static string CooperationTab2BodyText4 {
            get {
                return ResourceManager.GetString("CooperationTab2BodyText4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qualified specialists presenting registration department of our company,  support the registration of your product at the health authorities. We  offer consultations on all regulatory questions as well..
        /// </summary>
        public static string CooperationTab2BodyText5 {
            get {
                return ResourceManager.GetString("CooperationTab2BodyText5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONSULTING.
        /// </summary>
        public static string CooperationTab2BodyTitle {
            get {
                return ResourceManager.GetString("CooperationTab2BodyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data-driven decision making to ensure the best prospects of your company&apos;s business.
        /// </summary>
        public static string CooperationTab2Title {
            get {
                return ResourceManager.GetString("CooperationTab2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marketing &amp; Commercial Strategy.
        /// </summary>
        public static string CooperationTab3BodyText1Part1 {
            get {
                return ResourceManager.GetString("CooperationTab3BodyText1Part1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribution &amp; Sales.
        /// </summary>
        public static string CooperationTab3BodyText1Part2 {
            get {
                return ResourceManager.GetString("CooperationTab3BodyText1Part2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our core marketing competencies:.
        /// </summary>
        public static string CooperationTab3BodyText2 {
            get {
                return ResourceManager.GetString("CooperationTab3BodyText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our specialists from marketing and sales departments, perform marketing research, taking into account manufacturer&apos;s needs, and develop commercial strategy and ensure sales on the new markets..
        /// </summary>
        public static string CooperationTab3BodyText3 {
            get {
                return ResourceManager.GetString("CooperationTab3BodyText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MARKETING AND DISTRIBUTION.
        /// </summary>
        public static string CooperationTab3BodyTitle {
            get {
                return ResourceManager.GetString("CooperationTab3BodyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Making healthcare innovations available.
        /// </summary>
        public static string CooperationTab3Title {
            get {
                return ResourceManager.GetString("CooperationTab3Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXPERIENCED TEAM.
        /// </summary>
        public static string CooperationTab4BodyText1 {
            get {
                return ResourceManager.GetString("CooperationTab4BodyText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Since SafiMed’s insurance policies against financial (as well as logistical) risks are EU-validated, our partners encounter no technical challenges and enjoy all the prescribed guarantees..
        /// </summary>
        public static string CooperationTab4BodyText10 {
            get {
                return ResourceManager.GetString("CooperationTab4BodyText10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our staff with previous experience in national and multinational companies offers collective expertise in practical medicine, consulting, registration, marketing and distribution. This allows us achieve the goals set by our partners..
        /// </summary>
        public static string CooperationTab4BodyText2 {
            get {
                return ResourceManager.GetString("CooperationTab4BodyText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EFFICIENT NETWORK.
        /// </summary>
        public static string CooperationTab4BodyText3 {
            get {
                return ResourceManager.GetString("CooperationTab4BodyText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The efficiency is reached by activity of our regional managers and partners, and by strong established distribution network..
        /// </summary>
        public static string CooperationTab4BodyText4 {
            get {
                return ResourceManager.GetString("CooperationTab4BodyText4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMPLIANCE.
        /// </summary>
        public static string CooperationTab4BodyText5 {
            get {
                return ResourceManager.GetString("CooperationTab4BodyText5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We act with commitment to ethics and other principles accepted in our clients&apos; and partners&apos; companies..
        /// </summary>
        public static string CooperationTab4BodyText6 {
            get {
                return ResourceManager.GetString("CooperationTab4BodyText6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMPREHENSIVE BUSINESS SOLUTIONS.
        /// </summary>
        public static string CooperationTab4BodyText7 {
            get {
                return ResourceManager.GetString("CooperationTab4BodyText7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We provide integrated approach taking into account customer&apos;s individual needs. We pride ourselves on the quality of service rendered to our partners and clients..
        /// </summary>
        public static string CooperationTab4BodyText8 {
            get {
                return ResourceManager.GetString("CooperationTab4BodyText8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RISK PREVENTION.
        /// </summary>
        public static string CooperationTab4BodyText9 {
            get {
                return ResourceManager.GetString("CooperationTab4BodyText9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OUR CORE BENEFITS.
        /// </summary>
        public static string CooperationTab4BodyTitle {
            get {
                return ResourceManager.GetString("CooperationTab4BodyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsibility-Expertise-Reliability.
        /// </summary>
        public static string CooperationTab4Title {
            get {
                return ResourceManager.GetString("CooperationTab4Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «SafiMed» SIA.
        /// </summary>
        public static string CopyrightFooter {
            get {
                return ResourceManager.GetString("CopyrightFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CORE BENEFITS.
        /// </summary>
        public static string CoreBenefits {
            get {
                return ResourceManager.GetString("CoreBenefits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full compliance with the corporate culture, goals and values of our partner..
        /// </summary>
        public static string CoreBenefitsText {
            get {
                return ResourceManager.GetString("CoreBenefitsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to info@safi-med.com.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En.
        /// </summary>
        public static string En {
            get {
                return ResourceManager.GetString("En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All rights reserved..
        /// </summary>
        public static string FooterRights {
            get {
                return ResourceManager.GetString("FooterRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email Address.
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating high-tech products, manufacturers need a professional qualified promoter, who can make the product available for consumer - for both doctors and patients. Given the evolving trends across healthcare communities, you need a forward-thinking strategic partner that goes beyond traditional outsourcing, which offers &quot;full-cycle support&quot; service. Our integral feature is the development and promotion of partners’ business in the new markets. To address the complexity of our markets, we go deeper to develo [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MainBody {
            get {
                return ResourceManager.GetString("MainBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I propose to make here what some information with a brief description and a possible transition to what a tab.
        /// </summary>
        public static string MainSlider1Description {
            get {
                return ResourceManager.GetString("MainSlider1Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHARMACEUTICALS.
        /// </summary>
        public static string MainSlider1Text {
            get {
                return ResourceManager.GetString("MainSlider1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BIOCHEMICAL PRODUCTS.
        /// </summary>
        public static string MainSlider2Text {
            get {
                return ResourceManager.GetString("MainSlider2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PERSONAL HEALTH &amp; BEAUTY CARE.
        /// </summary>
        public static string MainSlider3Text {
            get {
                return ResourceManager.GetString("MainSlider3Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Making healthcare innovations available.
        /// </summary>
        public static string MainSlider4Text {
            get {
                return ResourceManager.GetString("MainSlider4Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MEDICAL DEVICES.
        /// </summary>
        public static string MainSlider5Text {
            get {
                return ResourceManager.GetString("MainSlider5Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We help to realize innovations in medical practice and make them available to public health.
        /// </summary>
        public static string MainTitle {
            get {
                return ResourceManager.GetString("MainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending of message failed!.
        /// </summary>
        public static string MessageSendError {
            get {
                return ResourceManager.GetString("MessageSendError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message successfully sended!.
        /// </summary>
        public static string MessageSendSuccess {
            get {
                return ResourceManager.GetString("MessageSendSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field is required..
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ru.
        /// </summary>
        public static string Ru {
            get {
                return ResourceManager.GetString("Ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SafiMed - About Us.
        /// </summary>
        public static string TitleAbout {
            get {
                return ResourceManager.GetString("TitleAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SafiMed - Contacts.
        /// </summary>
        public static string TitleContact {
            get {
                return ResourceManager.GetString("TitleContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SafiMed - Cooperation.
        /// </summary>
        public static string TitleCooperation {
            get {
                return ResourceManager.GetString("TitleCooperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SafiMed - Home.
        /// </summary>
        public static string TitleHome {
            get {
                return ResourceManager.GetString("TitleHome", resourceCulture);
            }
        }
    }
}
